name: trend
channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - jupyter
  - matplotlib
  - seaborn
  - mypy
  - numpy
  - pytest
  - python>=3.7
  - pandas
  - scikit-learn
  - boto3
  - pyyaml
  - plotly
  - pip
  - geopandas
  - statsmodels
  - pytorch
  - pip:
    - folium